// The different types of operations available
typedef enum valid_operations {RECEIVEFILE,VERIFY,REVOKE,REGISTER,GIVE, GETDIRECTORIES,CREATEDIRECTORY,CHECKA,DELETE, EXIT, CLIENTUPLOADFILE, CLIENTRECIVEFILE,SENDFILE, CLIENT_SHOW_DIRECTORIES, NAMEFILE} operation_t;

// The types of responses available
typedef enum valid_responses {CORRECT,INCORRECT,WRITTEN,ASK_ACCOUNT,FOUND,NOFOUND, BYE, ERROR,ASK, MENU,REGISTERS, DELOK} response_t;
